"""small update with penalty column

Revision ID: 84431a80fc6e
Revises: bb5d2b80e566
Create Date: 2025-09-26 18:03:26.333484

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84431a80fc6e'
down_revision: Union[str, Sequence[str], None] = 'bb5d2b80e566'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payrolls', 'penalty')
    op.add_column('salary_payments', sa.Column('penalty', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('salary_payments', 'penalty')
    op.add_column('payrolls', sa.Column('penalty', sa.NUMERIC(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
