"""Employee table migration

Revision ID: 969f35c069af
Revises: 612f0bef5470
Create Date: 2025-09-22 19:07:20.785475

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '969f35c069af'
down_revision: Union[str, Sequence[str], None] = '612f0bef5470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tab_number', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('middle_name', sa.String(length=64), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('passport_id', sa.String(length=64), nullable=False),
    sa.Column('passport_issued_by', sa.String(length=255), nullable=False),
    sa.Column('passport_issued_day', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('position_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tab_number')
    )
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_table('employees')
    # ### end Alembic commands ###
