"""SalaryPayment table

Revision ID: bb5d2b80e566
Revises: a685345fd89f
Create Date: 2025-09-26 13:14:55.194739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb5d2b80e566'
down_revision: Union[str, Sequence[str], None] = 'a685345fd89f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('salary_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payroll_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount_paid', sa.Numeric(), nullable=False),
    sa.ForeignKeyConstraint(['payroll_id'], ['payrolls.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_payments_id'), 'salary_payments', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_salary_payments_id'), table_name='salary_payments')
    op.drop_table('salary_payments')
    # ### end Alembic commands ###
