"""Implemented relations

Revision ID: c9d11f7912f4
Revises: 969f35c069af
Create Date: 2025-09-22 19:08:08.994954

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9d11f7912f4'
down_revision: Union[str, Sequence[str], None] = '969f35c069af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('head_id', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'departments', ['head_id'])
    op.create_foreign_key(None, 'departments', 'employees', ['head_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_constraint(None, 'departments', type_='unique')
    op.drop_column('departments', 'head_id')
    # ### end Alembic commands ###
